# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'ApplianceSmash iOS' do
pod ‘Mixpanel’
end

target 'ApplianceSmash Android' do

end

target 'ApplianceSmash Mac' do

end

